[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='generate_basic', game='Manual_TheLegendofZeldaEchoesofWisdomEchoHunt_killedragon')"]]
__expected__ = "fail"
__version__ = ">=0.0.3"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='pre_fill', game='Manual_TheLegendofZeldaEchoesofWisdomEchoHunt_killedragon')"]]
__expected__ = "fail"
__version__ = ">=0.0.3"

[["test.general.test_locations.TestBase.test_location_group [Triforce] (group_name='Triforce', game_name='Manual_TheLegendofZeldaEchoesofWisdomEchoHunt_killedragon')"]]
__expected__ = "fail"
__version__ = ">=0.0.3"
